### ISSUE TITLE
a

### ISSUE THREAD

**Issue by maya0177** [osu-datenshi/yohane#13]
pls stop using broken code

- chiisai dev

**Comment by troke12** [comment]
why?

**Comment by maya0177** [comment]
i really don't like seeing my years old shit code being used

**Comment by troke12** [comment]
Bruh, we already shutdown, so.. your code are not used again, but it's help us anyway, your code are not broken it's goodOn Dec 21, 2020 12:42 AM, Maya Copeland <notifications@github.com> wrote:
i really don't like seeing my years old shit code being used
